### ISSUE TITLE
GET /user/student/me

### ISSUE THREAD

**Issue by songsunkook** [BCSDLab/KOIN_API_V2#22]
# 어떤 이슈인가요?

학생 정보 조회

## 상위 이슈

#1

**Comment by Choi-JJunho** [comment]
## 특이사항
@Invidam 
다음 작업으로 해당하는 이슈에 달아둘게요~

**From**
- https://github.com/BCSDLab/KOIN_API_V2/pull/50

### TODO

- DB에 저장되어 있는 비밀번호 암호화 (로그인 시 PasswordEncoder를 통해 암호화된 값 비교 로직)
- 로그인 이후 서비스에 접근 시 ArgumentResolver 혹은 Filter에서 토큰 검증
