### ISSUE TITLE
기존 코인 API 마이그레이션을 완료한다.

### ISSUE THREAD

**Issue by songsunkook** [BCSDLab/KOIN_API_V2#25]
# 어떤 이슈인가요?

기존 코인에 존재하는 API들의 마이그레이션을 완료한다.

## 진행 상황

- [x] #2   
- [x] #43
- [x] #51
- [x] #72
- [x] #81
- [x] #483 
- [x] #96
- [x] #98
- [x] #103
- [x] #107
- [x] #110
- [x] #125
- [x] #145
- [x] #142
- [x] #115
- [x] #128
- [x] #35
- [x] #28
- [x] #42
- [x] #6 
- [x] #1 
- [x] #4

**Comment by Invidam** [comment]
KakaoBotController도 있어용
