### ISSUE TITLE
[백엔드] health check를 위한 spring actuator 추가

### ISSUE THREAD

**Issue by Choi-JJunho** [BCSDLab/KOIN_API_V2#275]
Production에 아래 자료를 참고하여 무중단배포한경을 구성했습니다.

https://blog.pium.life/dont-stop-deploy/

health check를 위한 spring actuator 의존성을 추가해줘야합니다

**Comment by johnny19991006** [comment]
첫 pr의 영광을 요것으로 가져가겠습니다~!
