### ISSUE TITLE
Normal 시간표 API를 구현한다.

### ISSUE THREAD

**Issue by songsunkook** [BCSDLab/KOIN_API_V2#28]
# 어떤 이슈인가요?

Normal 시간표 API를 구현한다.

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/4021b3c1-6e2c-4c5e-8317-9342bfb87d81)

- [x] #29
- [x] #30
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34

> 구체적인 내용은 아래 Swagger 참고
https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_TimeTable

**Comment by Invidam** [comment]
적당한 난이도

**Comment by songsunkook** [comment]
### 참고
semester_date -> (연도 4자리)(학기 1자리)
ex) 20241 -> 2024년도 1학기, 20192 -> 2019년도 2학기
![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/d73c6f56-e8b7-43dc-8751-bcf652b38e8c)
