### ISSUE TITLE
Normal 상점 API를 구현한다.

### ISSUE THREAD

**Issue by songsunkook** [BCSDLab/KOIN_API_V2#35]
# 어떤 이슈인가요?

Normal 상점 API를 구현한다.

![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/989d750d-1c73-4ea1-ad10-d8f949b87b0b)

- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41

> 구체적인 내용은 아래 Swagger 참고
https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_Shop

**Comment by Invidam** [comment]
depth가 좀 있어서 어려울 수도 있을 듯
